# Generated by Django 4.2.7 on 2025-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avilable',
            field=models.BooleanField(default=True),
        ),
    ]
