# Generated by Django 4.2.7 on 2025-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products_avilable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='about_cat',
            field=models.TextField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default='Default Category', max_length=200),
            preserve_default=False,
        ),
    ]
